# Node CircleCI 2.0 configuration file to DTA cloud 2.0

version: 2
jobs:

  # DEPLOY-STAGING JOB
  # installing dependencies, building assets and deploying to staging
  deploy-staging:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout                       # get the files from the repo (why would you ever not want the files????)
      - run: cd assess
      - run: rm -rf node_modules       # delete node_modules to bust caching
      - run: npm install               # duh
      - run: npm run build             # required build step
      - run: rm -rf node_modules       # delete node_modules folder again to not push it to cf
      - run: sudo apt-get install apt-transport-https
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf-cli
      - run: cd dist
      - run: cf install-plugin https://github.com/govau/autopilot/releases/download/0.0.5-venapp/autopilot-linux -f
      - run: cf version                # log what version we are running
      - run: cf login -a api.system.y.cld.gov.au -o $CF_ORG -s $CF_SPACE -u $CF_USER -p $CF_PASSWORD
      - run: cf push

  # DEPLOY-PRODUCTION JOB
  # installing dependencies, building assets and deploying to production
  deploy-prod:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout
      - run: cd assess
      - run: rm -rf node_modules
      - run: npm install
      - run: npm run build
      - run: rm -rf node_modules
      - run: sudo apt-get install apt-transport-https
      - run: wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
      - run: echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
      - run: sudo apt-get update
      - run: sudo apt-get install cf-cli
      - run: cf install-plugin https://github.com/govau/autopilot/releases/download/0.0.5-venapp/autopilot-linux -f
      - run: cf version
      - run: cf login -a api.system.b.cld.gov.au -o $CF_ORG_PROD -s $CF_SPACE_PROD -u $CF_USER_PROD -p $CF_PASSWORD_PROD
      - run: cf push



# OUR WORKFLOW
# this is where we orchestrate our jobs
workflows:
  version: 2
  deploying:
    jobs:
      - deploy-staging:       # run deploy staging
          filters:
            branches:
              only: develop   # and only on the `develop` branch

      - deploy-prod:          # run deploy production
          filters:
            branches:
              only: master    # and only on the `master` branch

