
# Angular parts from
# https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/continuous-integration.md#using-circle-ci

version: 2
jobs:
  build_test:
    docker:
      # specify the version you desire here
      # see https://hub.docker.com/r/circleci/node/tags/
      - image: circleci/node:10-browsers
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v0-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v0-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v0-dependencies-{{ checksum "package.json" }}

      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
      - run: npm run build

      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .
  deploy:
    docker:
      - image: govau/cf-cli
    working_directory: /root
    steps:
      - attach_workspace:
          at: /root
      - run:
          name: Deploying to cloud.gov.au
          command: /root/scripts/deploy.sh
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build_test
      - deploy:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
